### ISSUE TITLE
Logician: replace "not" modes with a not output

### ISSUE THREAD

**Issue by glocke01** [BlushAudioLab/BlushAudioVCVFreeModules#3]
One option for Logician would be to have two outputs and fewer modes. You wouldn't need a XNOR mode if there were a XOR output with a XNOR output right next to it. 

Alternatively, you could keep the jacks the same and reduce the legend using a "two-color LED" where "Yellow OR" means OR and "Red OR" is NOR. 

Just a thought. Thanks for your effort!

**Comment by BlushAudioLab** [comment]
That's a great suggestion. I really like the idea of having the inverted states on their own output. It could make the GUI a lot neater by having fewer modes to scroll through, as you say.

I'll this to the project board for the next update.

Thanks!

**Comment by BlushAudioLab** [comment]
Changes implemented now, and updated to V2.1.1. Hope you like the new version!
